name: 'Usage Statistics Tracker'
description: 'Track download statistics across multiple platforms (NPM, GitHub, PyPI, PowerShell)'
author: 'LukeHagar'

inputs:
  # NPM Configuration
  npm-packages:
    description: 'Comma-separated list of NPM packages to track'
    required: false
    default: ''
  
  # GitHub Configuration
  github-repositories:
    description: 'Comma-separated list of GitHub repositories (format: owner/repo)'
    required: false
    default: ''
  
  # PyPI Configuration
  pypi-packages:
    description: 'Comma-separated list of PyPI packages to track'
    required: false
    default: ''
  
  # PowerShell Configuration
  powershell-modules:
    description: 'Comma-separated list of PowerShell modules to track'
    required: false
    default: ''
  
  # Go tracking removed
  
  # Output paths
  json-output-path:
    description: 'Path for JSON output file'
    required: false
    default: 'stats.json'  
  readme-path:
    description: 'Path to README file to update'
    required: false
    default: 'README.md'
  
  # README update
  update-readme:
    description: 'Whether to update README.md with statistics'
    required: false
    default: 'true'
  
  # GitHub integration
  github-token:
    description: 'GitHub token for API access and commits'
    required: false
    default: '${{ github.token }}'
  
  # Commit settings
  commit-message:
    description: 'Commit message for changes'
    required: false
    default: 'chore: update usage statistics'

outputs:
  json-output:
    description: 'Path to the generated JSON file'
  
  platforms-tracked:
    description: 'Comma-separated list of platforms tracked'

runs:
  using: 'node20'
  main: 'dist/action.js' 