name: 'Usage Statistics Tracker'
description: 'Track download statistics across multiple platforms (NPM, GitHub, PyPI, Homebrew, PowerShell, Postman, Go)'
author: 'Your Name'

inputs:
  # Configuration
  config:
    description: 'Configuration for tracking (development, production, test, or custom JSON)'
    required: false
    default: 'production'
  
  # Output paths
  json-output-path:
    description: 'Path for JSON output file'
    required: false
    default: 'stats.json'
  
  csv-output-path:
    description: 'Path for CSV output file'
    required: false
    default: ''
  
  report-output-path:
    description: 'Path for human-readable report file'
    required: false
    default: ''
  
  # README update
  update-readme:
    description: 'Whether to update README.md with statistics'
    required: false
    default: 'true'
  
  readme-path:
    description: 'Path to README file to update'
    required: false
    default: 'README.md'
  
  # GitHub integration
  github-token:
    description: 'GitHub token for API access and commits'
    required: false
    default: '${{ github.token }}'
  
  # Postman integration
  postman-api-key:
    description: 'Postman API key for collection statistics'
    required: false
  
  # Commit settings
  commit-message:
    description: 'Commit message for changes'
    required: false
    default: 'chore: update usage statistics [skip ci]'
  
  # Preview mode
  preview-mode:
    description: 'Run in preview mode with mock data (no external API calls)'
    required: false
    default: 'false'

outputs:
  json-output:
    description: 'Path to the generated JSON file'
  
  csv-output:
    description: 'Path to the generated CSV file'
  
  report-output:
    description: 'Path to the generated report file'
  
  total-downloads:
    description: 'Total downloads across all platforms'
  
  unique-packages:
    description: 'Number of unique packages tracked'
  
  platforms-tracked:
    description: 'Comma-separated list of platforms tracked'

runs:
  using: 'node20'
  main: 'dist/index.js' 