[install]
# Use exact versions for reproducible builds
exact = true

[install.scopes]
# Configure any scoped packages if needed

[test]
# Test configuration
preload = ["./src/test-setup.ts"]

[run]
# Runtime configuration
bun = true 